---
- hosts: all
  become: true

  vars:
    user: root

  tasks:
    - name: Add Jenkins repository
      apt_repository:
        repo: "deb http://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Add Jenkins repository key
      apt_key:
        url: "https://pkg.jenkins.io/debian/jenkins.io.key"
        state: present

    - name: yum update
      yum:
        name: '*'
        state: latest
  
    - name: Install java
      yum:
        name: java-11-openjdk-devel
        state: present

    - name: Install jenkins
      yum:
        name: jenkins
        state: latest

    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started